MOUSEKEY_ENABLE     = no      # Mouse keys
RGBLIGHT_ENABLE     = yes     # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
OLED_ENABLE         = no
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = yes
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
