VIA_ENABLE = yes
VIAL_ENABLE = yes

# must reduce EEPROM usage
LTO_ENABLE = yes
QMK_SETTINGS = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
