VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes

LTO_ENABLE = yes

VIALRGB_ENABLE = yes

COMBO_ENABLE = no
QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
